### ISSUE TITLE
ایران سنس

### ISSUE THREAD

**Issue by amir-hossein-rajaezadeh** [mahdyar/persian-fonts-flutter#5]

**Comment by mahdyar** [comment]
Hello @AmirAndroidDeveloper;
I'm not sure what you mean by just opening an issue with the font's name, but I guess you want me to add it to the package, in that case, I'm afraid it's not possible since "IRANSans" is not a free font and is licensed.

سلام @AmirAndroidDeveloper؛
من مطمئن نیستم منظورتون از باز کردن این ایشو چی هست، ولی احتمالاً می‌خواید که فونت «ایران‌سنس» رو به پکیج اضافه کنم، در اون حالت متاسفانه باید بگم این کار امکان پذیر نیست چون این فونت، یک فونت رایگان و آزاد نیست و لایسنس داره.
